<?php

namespace tkanstantsin\fileupload\model;

/**
 * Class Alias
 * @todo: implement in filemanager.
 */
class Alias
{
    /**
     * Max file size in bytes
     * @var int
     */
    public $maxSize;
    /**
     * Max file count
     * @var int
     */
    public $maxCount;
    /**
     * Length of hash generated by hash method
     * @var int
     */
    public $hashLength;
    /**
     * Hash method like crc32 or md5
     * @var string
     */
    public $hashMethod;
    /**
     * Whether it is allowed multiple files for one model
     * @var bool
     */
    public $multiple;
}